=== panicmilos/vakcinac.io/xsd/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
  targetNamespace="http://euprava.org/izvestaj_o_imunizaciji" 
  xmlns="http://euprava.org/izvestaj_o_imunizaciji"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:os="http://osnovna-sema.org" 
  elementFormDefault="qualified">
  <xsd:import namespace="http://osnovna-sema.org" schemaLocation="osnovna_sema.xsd"/>

  <xsd:element name="izvestaj-o-imunizaciji">
    <xsd:complexType>

      <xsd:sequence>
        <xsd:element name="statistika-zahteva">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="podneto" type="xsd:nonNegativeInteger"></xsd:element>
              <xsd:element name="primljeno" type="xsd:nonNegativeInteger"></xsd:element>
              <xsd:element name="izdato" type="xsd:nonNegativeInteger"></xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="statistika-doza">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="ukupno-izdatih-doza" type="xsd:nonNegativeInteger"></xsd:element>
              <xsd:element name="izdate-doze">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="doza" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:simpleContent>
                          <xsd:extension base="xsd:nonNegativeInteger">
                            <xsd:attribute name="redni-broj" type="xsd:nonNegativeInteger" />
                          </xsd:extension>
                        </xsd:simpleContent>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="statistika-proizvodjaca">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="proizvodjac" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="naziv" type="xsd:string"></xsd:element>
                    <xsd:element name="broj-doza" type="xsd:nonNegativeInteger"></xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute name="izdato" type="os:TdateString"></xsd:attribute>
      <xsd:attribute name="od" type="os:TdateString"></xsd:attribute>
      <xsd:attribute name="do" type="os:TdateString"></xsd:attribute>

    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== panicmilos/vakcinac.io/information-system/citizen/backend/src/main/resources/data/docs/izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/izvestaj_o_imunizaciji.xsl"?>
<izvestaj-o-imunizaciji
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
  xsi:schemaLocation="https://www.vakcinac-io.rs/izvestaj ../xsd/izvestaj_o_imunizaciji.xsd"
  xmlns="https://www.vakcinac-io.rs/izvestaj"
  xmlns:os="https://www.vakcinac-io.rs/osnovna-sema"
  
  xmlns:rdfos="https://www.vakcinac-io.rs/rdfs/deljeno/"
  xmlns:rdfioi="https://www.vakcinac-io.rs/rdfs/izvestaj/"

  about="https://www.vakcinac-io.rs/izvestaj/1"
  typeof="rdfos:IzvestajOImunizacijiDokument"

  izdato="11.09.2022."
  od="01.08.2021."
  do="01.09.2021."
>

  <link rel="rdfioi:izdao" href="https://www.vakcinac-io.rs/sluzbenici/2222222222221" typeof="rdfos:Sluzbenik" />

  <meta property="rdfioi:periodOd" datatype="xsd:date">2021-08-01</meta>
  <meta property="rdfioi:periodDo" datatype="xsd:date">2021-09-01</meta>
  <meta property="rdfioi:ukupnoDoza" datatype="xsd:integer">3225</meta>
  <meta property="rdfos:izdat" datatype="xsd:date">2022-09-11</meta>

  <statistika-zahteva>
    <podneto>2758</podneto>
    <primljeno>453</primljeno>
    <izdato>428</izdato>
  </statistika-zahteva>
  <statistika-doza>
    <ukupno-izdatih-doza>3225</ukupno-izdatih-doza>
    <izdate-doze>
      <doza redni-broj="1">1789</doza>
      <doza redni-broj="2">1276</doza>
      <doza redni-broj="3">160</doza>
    </izdate-doze>
  </statistika-doza>
  <statistika-proizvodjaca>
    <proizvodjac>
      <naziv>Pfizer, BioNTech</naziv>
      <broj-doza>1625</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>Sinopharm</naziv>
      <broj-doza>1100</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>Sputnik V</naziv>
      <broj-doza>356</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>AstraZeneca, Oxford</naziv>
      <broj-doza>144</broj-doza>
    </proizvodjac>
  </statistika-proizvodjaca>
</izvestaj-o-imunizaciji>

=== panicmilos/vakcinac.io/xml/izvestaj_o_imunizaciji.xml
<?xml version="1.0" encoding="UTF-8"?>
<izvestaj-o-imunizaciji
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://euprava.org/izvestaj_o_imunizaciji ../xsd/izvestaj_o_imunizaciji.xsd"
  xmlns="http://euprava.org/izvestaj_o_imunizaciji"
  xmlns:os="http://osnovna-sema.org"
  izdato="11.09.2022"
  od="01.08.2021"
  do="01.09.2021"
>
  <statistika-zahteva>
    <podneto>2758</podneto>
    <primljeno>453</primljeno>
    <izdato>428</izdato>
  </statistika-zahteva>
  <statistika-doza>
    <ukupno-izdatih-doza>3225</ukupno-izdatih-doza>
    <izdate-doze>
      <doza redni-broj="1">1789</doza>
      <doza redni-broj="2">1276</doza>
      <doza redni-broj="3">160</doza>
    </izdate-doze>
  </statistika-doza>
  <statistika-proizvodjaca>
    <proizvodjac>
      <naziv>Pfizer, BioNTech</naziv>
      <broj-doza>1625</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>Sinopharm</naziv>
      <broj-doza>1100</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>Sputnik V</naziv>
      <broj-doza>356</broj-doza>
    </proizvodjac>
    <proizvodjac>
      <naziv>AstraZeneca, Oxford</naziv>
      <broj-doza>144</broj-doza>
    </proizvodjac>
  </statistika-proizvodjaca>
</izvestaj-o-imunizaciji>
