=== panicmilos/vakcinac.io/xsd/saglasnost_imunizacije.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    targetNamespace="http://euprava.org/saglasnost_imunizacije" 
    xmlns="http://euprava.org/saglasnost_imunizacije"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:os="http://osnovna-sema.org" 
    elementFormDefault="qualified">
    <xsd:import namespace="http://osnovna-sema.org" schemaLocation="osnovna_sema.xsd"/>

    <xsd:simpleType name="TradniStatus">
        <xsd:restriction base="xsd:int">
            <xsd:enumeration value="0"/>
            <xsd:enumeration value="1"/>
            <xsd:enumeration value="2"/>
            <xsd:enumeration value="3"/>
            <xsd:enumeration value="4"/>
            <xsd:enumeration value="5"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Tzanimanje">
        <xsd:restriction base="xsd:int">
            <xsd:enumeration value="0"/>
            <xsd:enumeration value="1"/>
            <xsd:enumeration value="2"/>
            <xsd:enumeration value="3"/>
            <xsd:enumeration value="4"/>
            <xsd:enumeration value="5"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="Tekstremitet">
        <xsd:restriction base="xsd:int">
            <xsd:enumeration value="0"/>
            <xsd:enumeration value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="saglasnost-za-sprovodjenje-preporucene-imunizacije">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="pacijent">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="drzavljanstvo">
                                <xsd:complexType>
                                    <xsd:choice minOccurs="1" maxOccurs="1">
                                        <xsd:element name="domace">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="jmbg" type="os:Tjmbg"></xsd:element>   
                                                </xsd:sequence>
                                            </xsd:complexType>      
                                        </xsd:element>
                                        <xsd:element name="strano">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="naziv-drzavljanstva" type="xsd:string"></xsd:element>
                                                    <xsd:element name="broj-pasosa-ebs" type="os:Tpasos"></xsd:element>      
                                                </xsd:sequence>
                                            </xsd:complexType>      
                                        </xsd:element>
                                    </xsd:choice>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="licne-informacije">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="prezime" type="xsd:string"></xsd:element>
                                        <xsd:element name="ime" type="xsd:string"></xsd:element>
                                        <xsd:element name="ime-roditelja" type="xsd:string"></xsd:element>
                                        <xsd:element name="pol" type="os:Tpol"></xsd:element>
                                        <xsd:element name="radni-status" type="TradniStatus"></xsd:element>
                                        <xsd:element name="zanimanje" type="Tzanimanje"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="rodjenje">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="datum-roÄ‘enja" type="os:Tdatum"></xsd:element>
                                        <xsd:element name="mesto-rodjenja" type="xsd:string"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="stanovanje">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="adresa" type="xsd:string"></xsd:element>
                                        <xsd:element name="mesto" type="xsd:string"></xsd:element>
                                        <xsd:element name="opstina" type="xsd:string"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="kontakt" type="os:Tkontakt"></xsd:element>

                            <xsd:element name="ustanova-socijalne-zastite">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="korisnik" type="xsd:boolean"></xsd:element>
                                        <xsd:element name="naziv-opstina-sedista" type="xsd:string"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="izjava-saglasnosti">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="izjava" type="xsd:boolean"></xsd:element>
                            <xsd:element name="naziv-imunoloskog-leka" type="xsd:string"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="evidencija-o-vakcinaciji">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="zdravstvena-ustanova" type="xsd:string"></xsd:element>
                            <xsd:element name="vakcinacijski-punkt" type="xsd:string"></xsd:element>
                            <xsd:element name="lekar">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="ime" type="xsd:string"></xsd:element>
                                        <xsd:element name="prezime" type="xsd:string"></xsd:element>
                                        <xsd:element name="faksimil" type="xsd:string"></xsd:element>
                                        <xsd:element name="broj-telefona" type="os:TbrMob"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="obrazac">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="primljene-vakcine" minOccurs="1" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="naziv" nillable="true" type="xsd:string"></xsd:element>
                                                    <xsd:element name="datum-davanja-vakcine" nillable="true" type="os:Tdatum"></xsd:element>
                                                    <xsd:element name="nacin-davanja-vakcine" nillable="true" type="xsd:string"></xsd:element>
                                                    <xsd:element name="ekstremitet" nillable="true" type="Tekstremitet"></xsd:element>
                                                    <xsd:element name="serija-vakcine" nillable="true" type="xsd:string"></xsd:element>
                                                    <xsd:element name="proizvodjac" nillable="true" type="xsd:string"></xsd:element>
                                                    <xsd:element name="nezeljena-reakcija" nillable="true" type="xsd:string"></xsd:element>
                                                </xsd:sequence>
                                                <xsd:attribute name="broj" type="xsd:int"></xsd:attribute>
                                            </xsd:complexType>
                                        </xsd:element>
                                        
                                        <xsd:element name="privremene-kontraindikacije">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="datum-utvrdjivanja" nillable="true" type="os:Tdatum"></xsd:element>
                                                    <xsd:element name="dijagnoza" nillable="true" type="xsd:string"></xsd:element>
                                                    <xsd:element name="odluka-komisije" nillable="true" type="xsd:boolean"></xsd:element>
                                                </xsd:sequence>
                                                <xsd:attribute name="broj" type="xsd:int"></xsd:attribute>
                                            </xsd:complexType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>

            <xsd:attribute name="datum-izdavanja" type="os:TdateString"></xsd:attribute>

        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== panicmilos/vakcinac.io/xml/saglasnost_za_sprovodjenje_preporucene_imunizacije.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/saglasnost_imunizacije.xsl"?>
<saglasnost-za-sprovodjenje-preporucene-imunizacije
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/"
    xsi:schemaLocation="https://www.vakcinac-io.rs/saglasnost/ ../xsd/saglasnost_imunizacije.xsd"
    xmlns="https://www.vakcinac-io.rs/saglasnos/t"
    xmlns:os="https://www.vakcinac-io.rs/osnovna-sema/"

    xmlns:rdfos="https://www.vakcinac-io.rs/rdfs/deljeno/"
    xmlns:rdfsi="https://www.vakcinac-io.rs/rdfs/saglasnost/"

    about="https://www.vakcinac-io.rs/saglasnost/2506123456789/1"
    typeof="rdfos:SaglasnostImunizacijeDokument"

    datum-izdavanja="17.11.2021."
>
    <link rel="rdfsi:naOsnovuInteresovanja" href="https://www.vakcinac-io.rs/interesovanje/2506123456789/1" typeof="rdfos:IzjavaInteresovanjaZaVakcinisanjeDokument" />
    <link rel="rdfsi:za" href="https://www.vakcinac-io.rs/gradjani/2506123456789" typeof="rdfos:Gradjanin" />
    <link rel="rdfsi:vakcinisanOd" href="https://www.vakcinac-io.rs/zdravstveni-radnici/123456" typeof="rdfos:ZdravstveniRadnik" />

    <meta property="rdfsi:izmenjen" datatype="xsi:date">2021-11-19</meta>
    <meta property="rdfos:izdat" datatype="xsi:date">2021-11-17</meta>

    <pacijent>
        <drzavljanstvo>
            <domace>
                <jmbg>2506123456789</jmbg>
            </domace>
        </drzavljanstvo>
        <licne-informacije>
            <os:ime>Лука</os:ime>
            <os:prezime>Шербеџија</os:prezime>
            <ime-roditelja>Петар</ime-roditelja>
            <pol>0</pol>
            <radni-status>4</radni-status>
            <zanimanje>5</zanimanje>
        </licne-informacije>
        <rodjenje>
            <datum-rodjenja>06.04.1999.</datum-rodjenja>
            <mesto-rodjenja>Нови Сад</mesto-rodjenja>
        </rodjenje>
        <stanovanje>
            <adresa>Светосавска 15</adresa>
            <mesto>Нови Сад</mesto>
            <opstina>Нови Сад</opstina>
        </stanovanje>
        <kontakt>
            <os:adresa-elektronske-poste>serbedzija@gmail.com</os:adresa-elektronske-poste>
            <os:broj-mobilnog-telefona>0624543632</os:broj-mobilnog-telefona>
            <os:broj-fiksnog-telefona>011277787</os:broj-fiksnog-telefona>
        </kontakt>
        <ustanova-socijalne-zastite>
            <korisnik>false</korisnik>
            <naziv-opstina-sedista></naziv-opstina-sedista>
        </ustanova-socijalne-zastite>
    </pacijent>
    <izjava-saglasnosti>
        <izjava>false</izjava>
        <naziv-imunoloskog-leka></naziv-imunoloskog-leka>
    </izjava-saglasnosti>

    <evidencija-o-vakcinaciji>
        <zdravstvena-ustanova>Дом здравља Јован Јовановић Змај</zdravstvena-ustanova>
        <vakcinacijski-punkt>Променада</vakcinacijski-punkt>
        <lekar>
            <os:ime>Ивко</os:ime>
            <os:prezime>Бањац</os:prezime>
            <faksimil>123456</faksimil>
            <broj-telefona>0624543632</broj-telefona>
        </lekar>
        <obrazac>
            <primljene-vakcine broj="1">
                <naziv xsi:nil="true"></naziv>
                <datum-davanja-vakcine xsi:nil="true"></datum-davanja-vakcine>
                <nacin-davanja-vakcine xsi:nil="true"></nacin-davanja-vakcine>
                <ekstremitet xsi:nil="true"></ekstremitet>
                <serija-vakcine xsi:nil="true"></serija-vakcine>
                <proizvodjac xsi:nil="true"></proizvodjac>
                <nezeljena-reakcija xsi:nil="true"></nezeljena-reakcija>
            </primljene-vakcine>
            <primljene-vakcine broj="2">
                <naziv xsi:nil="true"></naziv>
                <datum-davanja-vakcine xsi:nil="true"></datum-davanja-vakcine>
                <nacin-davanja-vakcine xsi:nil="true"></nacin-davanja-vakcine>
                <ekstremitet xsi:nil="true"></ekstremitet>
                <serija-vakcine xsi:nil="true"></serija-vakcine>
                <proizvodjac xsi:nil="true"></proizvodjac>
                <nezeljena-reakcija xsi:nil="true"></nezeljena-reakcija>
            </primljene-vakcine>
            <privremene-kontraindikacije>
                <datum-utvrdjivanja xsi:nil="true"></datum-utvrdjivanja>
                <dijagnoza xsi:nil="true"></dijagnoza>
                <odluka-komisije xsi:nil="true"></odluka-komisije>
            </privremene-kontraindikacije>
        </obrazac>
    </evidencija-o-vakcinaciji>
</saglasnost-za-sprovodjenje-preporucene-imunizacije>
